Corrected deployment code

diff --git a/deployCDN b/deployCDN
--- a/deployCDN
+++ b/deployCDN
@@ -1,33 +1,71 @@
 #!/bin/bash
+# Sample usage:
+# ./deployCDN -p 25019 -o cs5700cdnorigin.ccs.neu.edu -n cs5700cdn.example.com -u cdn_project_dileep_nikhil -i /Users/dileepshah/.ssh/id_ed25519
 
-username="cdn_project_dileep_nikhil"
-keyfile="/home/nikhil/.ssh/id_rsa"
-dns_server_ip_address="97.107.140.73"
-dns_build_path="/home/$username/p4_build"
-projectpath="/CS5700_Project4_OwnCDN"
-dns_files_to_copy=(dnsserver.py dns res)
-port=$2
-origin=$4
-name=$6
-username=$8
-keyfile=${10}
-
-echo "Deploying the CDN to "
-ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$dns_server_ip_address rm -rf $dns_build_path ;
-
-ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$dns_server_ip_address mkdir -p $dns_build_path ;
-ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$dns_server_ip_address pwd;
-
-
-for file in "${dns_files_to_copy[@]}"; do
-  echo "Copying $file to $dns_dns_build_path"
-    scp -o "StrictHostKeyChecking no" -i $keyfile -r $file $username@$dns_server_ip_address:$dns_build_path ;
-
-  echo "File copying is done!"
+while getopts ":p:o:n:u:i:" opt; do
+  case $opt in
+    p) port="$OPTARG"
+    ;;
+    o) origin="$OPTARG"
+    ;;
+    n) name="$OPTARG"
+    ;;
+    u) username="$OPTARG"
+    ;;
+    i) keyfile="$OPTARG"
+    ;;
+    \?) printf "Invalid option %s" "$OPTARG" >&2
+    ;;
+  esac
 done
 
+# Check if the port number is valid
+if [ "$port" -lt 1024 ] && [ "$port" -gt 65535 ]
+then
+    printf "Port number should be between 1024 and 65535"
+    exit 0
+fi
+
+# Check if the name is valid
+if [ -z "$name" ]
+then
+    printf "Name cannot be empty"
+    exit 0
+fi
+
+# Check if the username is valid
+if [ -z "$username" ]
+then
+    printf "Username cannot be empty"
+    exit 0
+fi
+
+# Check if the keyfile is valid
+if [ -z "$keyfile" ]
+then
+    printf "Keyfile cannot be empty"
+    exit 0
+fi
+
+dns_build_path="/home/$username/p4_build"
+
+#
+#echo "Deploying the CDN to "
+#ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$dns_server_ip_address rm -rf $dns_build_path ;
+#
+#ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$dns_server_ip_address mkdir -p $dns_build_path ;
+#ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$dns_server_ip_address pwd;
+#
+#
+#for file in "${dns_files_to_copy[@]}"; do
+#  echo "Copying $file to $dns_dns_build_path"
+#    scp -o "StrictHostKeyChecking no" -i $keyfile -r $file $username@$dns_server_ip_address:$dns_build_path ;
+#
+#  echo "File copying is done!"
+#done
+
 # Make the zip file of the source code and upload it to the dns server.
-file_name="p4.zip"
+http_files_to_copy=(replicas.txt httpreq httpserver httpserver.py utils Makefile)
 
 # Read the dns server IP address from the dns-hosts.txt file and copy the source code to the dns server.
 while IFS= read -r ip; do
@@ -36,8 +74,25 @@ while IFS= read -r ip; do
     continue
   fi
 
+  until ssh -n -o "StrictHostKeyChecking no" -i "$keyfile" "$username"@"$ip" rm -rf "$dns_build_path" ; do
+    sleep 1
+  done
+
+  until ssh -n -o "StrictHostKeyChecking no" -i "$keyfile" "$username"@"$ip" mkdir -p "$dns_build_path" ; do
+    sleep 1
+  done
+
+  until ssh -n -o "StrictHostKeyChecking no" -i "$keyfile" "$username"@"$ip" ls ; do
+    sleep 1
+  done
+
   # Copy the source code to the dns server.
   # scp -o "StrictHostKeyChecking no" -i $keyfile -r $file $username@$ip:$dns_build_path ;
+  for file_name in "${http_files_to_copy[@]}"; do
+    echo "Copying $file_name to $dns_build_path"
 
-  scp -o "StrictHostKeyChecking no" -i $keyfile $file_name $username@$dns_server_ip_address:$dns_build_path
-done < dns-hosts.txt
+    scp -o "StrictHostKeyChecking no" -i "$keyfile" -r "$file_name" "$username"@"$ip":"$dns_build_path";
+    echo "File copying is done!"
+  done
+
+done < replicas.txt
